# Change these first
owner: AmmbrFi # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Ammbr Finance
    url: https://ammbr.finance
  - name: Ammbr QMM
    url: https://qmm.ammbr.finance
  - name: Token Bridge
    url: https://swap-beta.ammbr.finance
  - name: Ammbr NFT
    url: https://nft.ammbr.finance

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.ammbr.finance
  logoUrl: https://nft.ammbr.finance/ammbr-logo.svg
  name: Status
  introTitle: ""
  introMessage: ""
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
